version: '3.3'
services:  
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    restart: unless-stopped
    hostname: mongodb
    ports:
      - "27017"
    command: --replSet rs0 --bind_ip_all
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
    networks:
      - echoes-tools
    volumes:
      - ./db:/data/db
  echoes:
    build:
      context: ./echoes-tools
      dockerfile: Dockerfile
    image: 'echoes/echoes-tools:1.8'
    container_name: echoes-tools
    hostname: echoes-tools
    volumes:
      - ${ECHOES_SOURCE_FOLDER}:${ECHOES_TARGET_FOLDER}/source:rw
    depends_on:
      - mongodb
    networks:
      - echoes-tools

networks:
  echoes-tools:
    driver: bridge
