version: '3.9'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
#      - ./echoes-portal/plugins/wp-mvc/:/var/www/html/wp-content/plugins/wp-mvc
      - ./echoes-portal/plugins/ECHOES-WP-SPARQL-Plugin/:/var/www/html/wp-content/plugins/ECHOES-WP-SPARQL-Plugin
      - ./echoes-portal/themes/echoes/:/var/www/html/wp-content/themes/echoes
      - ./echoes-portal/themes/echoes-child/:/var/www/html/wp-content/themes/echoes-child

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
