package org.csuc.util;

public enum MetadataType {

    rdf_about("rdf:about"),

    dc_contributor("dc:contributor"),
    dcterms_isReplacedBy("dcterms:isReplacedBy"),
    dc_coverage("dc:coverage"),
    dcterms_isRequiredBy("dcterms:isRequiredBy"),
    dc_creator("dc:creator"),
    dcterms_issued("dcterms:issued"),
    dc_date("dc:date"),
    dcterms_isVersionOf("dcterms:isVersionOf"),
    dc_description("dc:description"),
    dcterms_medium("dcterms:medium"),
    dc_format("dc:format"),
    dcterms_provenance("dcterms:provenance"),
    dc_identifier("dc:identifier"),
    dcterms_references("dcterms:references"),
    dc_language("dc:language"),
    dcterms_replaces("dcterms:replaces"),
    dc_publisher("dc:publisher"),
    dcterms_requires("dcterms:requires"),
    dc_relation("dc:relation"),
    dcterms_spatial("dcterms:spatial"),
    dc_rights("dc:rights"),
    dcterms_tableOfContents("dcterms:tableOfContents"),
    dc_source("dc:source"),
    dcterms_temporal("dcterms:temporal"),
    dc_subject("dc:subject"),
    edm_currentLocation("edm:currentLocation"),
    dc_title("dc:title"),
    edm_hasMet("edm:hasMet"),
    dc_type("dc:type"),
    edm_hasType("edm:hasType"),
    dcterms_alternative("dcterms:alternative"),
    edm_incorporates("edm:incorporates"),
    dcterms_conformsTo("dcterms:conformsTo"),
    edm_isDerivativeOf("edm:isDerivativeOf"),
    dcterms_created("dcterms:created"),
    edm_isNextInSequence("edm:isNextInSequence"),
    dcterms_extent("dcterms:extent"),
    edm_isRelatedTo("edm:isRelatedTo"),
    dcterms_hasFormat("dcterms:hasFormat"),
    edm_isRepresentationOf("edm:isRepresentationOf"),
    dcterms_hasPart("dcterms:hasPart"),
    edm_isSimilarTo("edm:isSimilarTo"),
    dcterms_hasVersion("dcterms:hasVersion"),
    edm_isSuccessorOf("edm:isSuccessorOf"),
    dcterms_isFormatOf("dcterms:isFormatOf"),
    edm_realizes("edm:realizes"),
    dcterms_isPartOf("dcterms:isPartOf"),
    edm_type("edm:type"),
    dcterms_isReferencedBy("dcterms:isReferencedBy"),
    owl_sameAs("owl:sameAs"),
    edm_aggregatedCHO("edm:aggregatedCHO"),
    edm_provider("edm:provider"),
    edm_dataProvider("edm:dataProvider"),
    edm_hasView("edm:hasView"),
    edm_rights("edm:rights"),
    edm_isShownAt("edm:isShownAt"),
    edm_ugc("edm:ugc"),
    edm_isShownBy("edm:isShownBy"),
    edm_intermediateProvider("edm:intermediateProvider"),
    edm_object("edm:object"),
    skos_prefLabel("skos:prefLabel"),
    foaf_name("foaf:name"),
    skos_altLabel("skos:altLabel"),
    rdaGr2_biographicalInformation("rdaGr2:biographicalInformation"),
    skos_note("skos:note"),
    rdaGr2_dateOfBirth("rdaGr2:dateOfBirth"),
    rdaGr2_dateOfDeath("rdaGr2:dateOfDeath"),
    rdaGr2_dateOfEstablishment("rdaGr2:dateOfEstablishment"),
    rdaGr2_dateOfTermination("rdaGr2:dateOfTermination"),
    rdaGr2_gender("rdaGr2:gender"),
    edm_begin("edm:begin"),
    rdaGr2_placeOfBirth("rdaGr2:placeOfBirth"),
    edm_end("edm:end"),
    rdaGr2_placeOfDeath("rdaGr2:placeOfDeath"),
    rdaGr2_professionOrOccupation("rdaGr2:professionOrOccupation"),
    wgs84_pos_lat("wgs84_pos:lat"),
    wgs84_pos_long("wgs84_pos:long"),
    wgs84_pos_alt("wgs84_pos:alt"),
    odrl_inheritFrom("odrl:inheritFrom"),
    cc_deprecatedOn("cc:deprecatedOn"),
    skos_relatedMatch("skos:relatedMatch"),
    skos_exactMatch("skos:exactMatch"),
    skos_broader("skos:broader"),
    skos_closeMatch("skos:closeMatch"),
    skos_narrower("skos:narrower"),
    skos_related("skos:related"),
    skos_notation("skos:notation"),
    skos_broadMatch("skos:broadMatch"),
    skos_inScheme("skos:inScheme"),
    skos_narrowMatch("skos:narrowMatch");

    private final String type;

    MetadataType(String type) {
        this.type = type;
    }

    public String getType() {
        return type;
    }
}
